# Proyecto Base de Datos para la OCDE

### Elaborado por Eva Lorena García

## Parte 1 - Presentación
Presentar resultados<br>
Método de resolución<br>
Algoritmo<br>
Gráficas<br>
DataFrame final<br>
Conclusiones<br>

## Parte 2 - Preámbulo

Que voy a hacer?

-Buscar patrones<br> -Buscar relaciones<br> -Cosas curiosas de los datos<br>

Qué usaré hoy?

In [5]:
#Empiezo importando todas las herramientas que voy a utilizar
#importando las librerias necesarias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Parte 3 - Análisis inicial

Parte 3 - Análisis inicial 

Presenta entrega el resultado y el código utilizado. Mientras más explícito, mejor. Mientras más bonito, mejor

¿Cuántos países hay en la base de datos? ¿Cuáles son?
¿Cuántos tipos de unidades se manejan?
¿Cuáles son los indicadores medidos? ¿Cuántos son?
Descripción básica de los indicadores numéricos (estadística descriptiva)
¿Podemos eliminar algunas columnas de nuestra base de datos sin perder información importante? Presenta la tabla y explica por qué eliminste dichas columnas
¿Puedes cambiar en nombre de las columnas a español?

In [33]:
#Cargar la base de datos, que se encuentra en la misma capeta
#como OCDE
OCDE=pd.read_csv('BLI.csv')

In [24]:
pd.DataFrame(OCDE)

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
1,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
2,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
3,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.90,NaN,NaN
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
5,DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.30,NaN,NaN
6,FIN,Finland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
7,FRA,France,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.00,NaN,NaN
8,DEU,Germany,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.00,NaN,NaN
9,GRC,Greece,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.40,NaN,NaN
10,HUN,Hungary,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
11,ISL,Iceland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
12,IRL,Ireland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
13,ITA,Italy,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,8.10,NaN,NaN
14,JPN,Japan,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.50,NaN,NaN
15,KOR,Korea,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.40,NaN,NaN
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.20,NaN,NaN
17,MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.90,NaN,NaN
20,NOR,Norway,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
21,POL,Poland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
22,PRT,Portugal,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.50,NaN,NaN
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.70,NaN,NaN
24,ESP,Spain,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.30,NaN,NaN
25,SWE,Sweden,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.70,NaN,NaN
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
27,TUR,Turkey,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,13.00,NaN,NaN
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
29,USA,United States,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

# ¿Cuántos países hay en la base de datos? ¿Cuáles son?

In [26]:
#Numero de paises en la OCDE 
#¿Cuántos países hay en la base de datos? ¿Cuáles son?
OCDE['Country'].unique()
TotPaises=len(OCDE['Country'].unique())-1
print("Paises en la OCDE {}".format(TotPaises))

Paises en la OCDE 38

38

In [29]:
#Numero de paises en la OCDE 
#¿Cuántos países hay en la base de datos? ¿Cuáles son?
NomPaises=OCDE['Country'].unique()
pd.DataFrame(NomPaises)

                  0
0         Australia
1           Austria
2           Belgium
3            Canada
4    Czech Republic
5           Denmark
6           Finland
7            France
8           Germany
9            Greece
10          Hungary
11          Iceland
12          Ireland
13            Italy
14            Japan
15            Korea
16       Luxembourg
17           Mexico
18      Netherlands
19      New Zealand
20           Norway
21           Poland
22         Portugal
23  Slovak Republic
24            Spain
25           Sweden
26      Switzerland
27           Turkey
28   United Kingdom
29    United States
30           Brazil
31            Chile
32          Estonia
33           Israel
34           Latvia
35           Russia
36         Slovenia
37     South Africa
38     OECD - Total

In [30]:
OCDE

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
1,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
2,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
3,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.90,NaN,NaN
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
5,DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.30,NaN,NaN
6,FIN,Finland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
7,FRA,France,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.00,NaN,NaN
8,DEU,Germany,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.00,NaN,NaN
9,GRC,Greece,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.40,NaN,NaN
10,HUN,Hungary,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
11,ISL,Iceland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
12,IRL,Ireland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
13,ITA,Italy,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,8.10,NaN,NaN
14,JPN,Japan,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.50,NaN,NaN
15,KOR,Korea,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.40,NaN,NaN
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.20,NaN,NaN
17,MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.90,NaN,NaN
20,NOR,Norway,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
21,POL,Poland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
22,PRT,Portugal,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.50,NaN,NaN
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.70,NaN,NaN
24,ESP,Spain,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.30,NaN,NaN
25,SWE,Sweden,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.70,NaN,NaN
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
27,TUR,Turkey,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,13.00,NaN,NaN
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
29,USA,United States,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

# ¿Cuántos tipos de unidades se manejan?

In [30]:
#¿Cuántos tipos de unidades se manejan? 
Unidades=OCDE['Unit'].unique()
print("Total de unidades manejadas= {}".format(len(Unidades)))
pd.DataFrame(Unidades)

Total de unidades manejadas= 7

                            0
0                  Percentage
1               Average score
2                       Ratio
3                   US Dollar
4                       Years
5  Micrograms per cubic metre
6                       Hours

# ¿Cuáles son los indicadores medidos? ¿Cuántos son?

In [7]:
#¿Cuáles son los indicadores medidos? ¿Cuántos son? 
Indicadores_medidos=OCDE['Indicator'].unique()
print("Total de indicadores medidos= {}".format(len(Indicadores_medidos)))
pd.DataFrame(Indicadores_medidos)

Total de indicadores medidos= 24

                                                    0
0                            Labour market insecurity
1   Stakeholder engagement for developing regulations
2                 Feeling safe walking alone at night
3                  Dwellings without basic facilities
4                                 Housing expenditure
5                                    Rooms per person
6            Household net adjusted disposable income
7                      Household net financial wealth
8                                     Employment rate
9                         Long-term unemployment rate
10                                  Personal earnings
11                         Quality of support network
12                             Educational attainment
13                                     Student skills
14                                 Years in education
15                                      Air pollution
16                                      Water quality
17                                      Voter turnout
18                                    Life expectancy
19                               Self-reported health
20                                  Life satisfaction
21                                      Homicide rate
22                  Employees working very long hours
23          Time devoted to leisure and personal care

# Descripción básica de los indicadores numéricos (estadística descriptiva)

In [8]:
#Descripción básica de los indicadores numéricos (estadística descriptiva) 
OCDE.describe()

       PowerCode Code  Reference Period Code  Reference Period          Value
count          3398.0                    0.0               0.0    3398.000000
mean              0.0                    NaN               NaN    5353.200309
std               0.0                    NaN               NaN   15832.099269
min               0.0                    NaN               NaN       0.000000
25%               0.0                    NaN               NaN       7.000000
50%               0.0                    NaN               NaN      62.000000
75%               0.0                    NaN               NaN      91.000000
max               0.0                    NaN               NaN  176076.000000

# ¿Podemos eliminar algunas columnas de nuestra base de datos sin perder información importante? Presenta la tabla y explica por qué eliminste dichas columnas

Sí es posible y de preferencia como buena práctica se recomienda crear un Dataset con una copia de la información, el cual podemos manipular a nuestro antojo. A continución eliminaré 5 columnas REPETIDAS por lo que realmente no existirá perdida alguna de información, además de que almacenaré los datos en un Dataset llamado OCDEBorrados:

In [37]:
#visualizacion de la BdD para evaluar que columnas voy a borrar
OCDE

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
1,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
2,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
3,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.90,NaN,NaN
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
5,DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.30,NaN,NaN
6,FIN,Finland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
7,FRA,France,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.00,NaN,NaN
8,DEU,Germany,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.00,NaN,NaN
9,GRC,Greece,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.40,NaN,NaN
10,HUN,Hungary,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
11,ISL,Iceland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
12,IRL,Ireland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
13,ITA,Italy,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,8.10,NaN,NaN
14,JPN,Japan,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.50,NaN,NaN
15,KOR,Korea,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.40,NaN,NaN
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.20,NaN,NaN
17,MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.90,NaN,NaN
20,NOR,Norway,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
21,POL,Poland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
22,PRT,Portugal,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.50,NaN,NaN
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.70,NaN,NaN
24,ESP,Spain,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.30,NaN,NaN
25,SWE,Sweden,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.70,NaN,NaN
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
27,TUR,Turkey,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,13.00,NaN,NaN
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
29,USA,United States,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

In [38]:
#Borrando columnas con el método drop, checar sintaxis
OCDEBorrados=OCDE.drop(['Unit Code','PowerCode Code','Reference Period Code','Reference Period','Flag Codes'],axis=1)

In [40]:
#visualización de datos borrados en el nuevo Dataset creado
pd.DataFrame(OCDEBorrados)

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit,PowerCode,Value,Flags
0,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.30,NaN
1,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.70,NaN
2,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.80,NaN
3,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,3.90,NaN
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,1.80,NaN
5,DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.30,NaN
6,FIN,Finland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.70,NaN
7,FRA,France,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,5.00,NaN
8,DEU,Germany,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.00,NaN
9,GRC,Greece,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,17.40,NaN
10,HUN,Hungary,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.80,NaN
11,ISL,Iceland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.60,NaN
12,IRL,Ireland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.10,NaN
13,ITA,Italy,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,8.10,NaN
14,JPN,Japan,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,1.50,NaN
15,KOR,Korea,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.40,NaN
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,3.20,NaN
17,MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.60,NaN
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.10,NaN
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.90,NaN
20,NOR,Norway,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.70,NaN
21,POL,Poland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.30,NaN
22,PRT,Portugal,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,6.50,NaN
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,6.70,NaN
24,ESP,Spain,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,17.30,NaN
25,SWE,Sweden,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,5.70,NaN
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,1.80,NaN
27,TUR,Turkey,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,13.00,NaN
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.60,NaN
29,USA,United States,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,3.80,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.42,Estimated value
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.82,Estimated value
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,13.87,Estimated value
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.06,Estimated value
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.29,NaN
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.53,NaN
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.00,NaN
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.92,Estimated value
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,12.39,Estimated value
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.71,Estimated value
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.95,NaN
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.65,NaN
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.08,NaN
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.64,Estimated value
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.77,Estimated value
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.48,NaN
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.23,NaN
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.78,Estimated value
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,12.22,Estimated value
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.86,NaN
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.39,NaN
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.18,Estimated value
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.66,Estimated value
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.43,NaN
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,13.63,Estimated value
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,13.45,NaN
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.66,Estimated value
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.17,NaN
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.37,NaN
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.60,NaN

# ¿Puedes cambiar en nombre de las columnas a español?

In [ ]:
Sí es posible, con el método rename. La sintaxis es Dataset.rename(columns={'nombre_antiguo':'nombre_nuevo'})

In [ ]:
#para esto creamos un dataset nuevo para manipularlo
OCDEspaniol=OCDE

In [45]:
#cambiar el nombre de la columna
OCDEspaniol= OCDEBorrados.rename(columns={'LOCATION':'LUGAR','Country':'Pais','INDICATOR':'INDICADOR','Indicator':'Indicador','MEASURE':'MEDIDA'})
OCDEspaniol=OCDEspaniol.rename(columns={'Measure':'Medida','INEQUALITY':'Desigualdad','Inequality':'Desigualdad','Unit':'Unidad','Value':'Valor'})

In [46]:
OCDEspaniol

,LUGAR,Pais,INDICADOR,Indicador,MEDIDA,Medida,DESIGUALDAD,DESIGUALDAD,Unidad,PowerCode,Valor,Flags
0,AUS,Australia,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.30,NaN
1,AUT,Austria,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.70,NaN
2,BEL,Belgium,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.80,NaN
3,CAN,Canada,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,3.90,NaN
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,1.80,NaN
5,DNK,Denmark,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.30,NaN
6,FIN,Finland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.70,NaN
7,FRA,France,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,5.00,NaN
8,DEU,Germany,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.00,NaN
9,GRC,Greece,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,17.40,NaN
10,HUN,Hungary,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.80,NaN
11,ISL,Iceland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.60,NaN
12,IRL,Ireland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.10,NaN
13,ITA,Italy,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,8.10,NaN
14,JPN,Japan,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,1.50,NaN
15,KOR,Korea,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.40,NaN
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,3.20,NaN
17,MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.60,NaN
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.10,NaN
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.90,NaN
20,NOR,Norway,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.70,NaN
21,POL,Poland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,4.30,NaN
22,PRT,Portugal,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,6.50,NaN
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,6.70,NaN
24,ESP,Spain,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,17.30,NaN
25,SWE,Sweden,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,5.70,NaN
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,1.80,NaN
27,TUR,Turkey,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,13.00,NaN
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,2.60,NaN
29,USA,United States,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,Percentage,Units,3.80,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.42,Estimated value
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.82,Estimated value
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,13.87,Estimated value
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.06,Estimated value
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.29,NaN
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.53,NaN
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.00,NaN
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.92,Estimated value
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,12.39,Estimated value
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.71,Estimated value
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.95,NaN
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.65,NaN
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.08,NaN
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.64,Estimated value
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.77,Estimated value
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.48,NaN
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,15.23,NaN
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.78,Estimated value
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,12.22,Estimated value
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.86,NaN
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.39,NaN
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.18,Estimated value
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.66,Estimated value
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.43,NaN
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,13.63,Estimated value
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,13.45,NaN
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.66,Estimated value
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.17,NaN
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.37,NaN
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,Hours,Units,14.60,NaN

## Parte 4 - Búsqueda de datos
Imprime el los datos o Dataframes ( ¡Panditas! :D ) que se te solicitan (Recuerden no modificar el original) y entregenme sus observacioens de los datos (pueden usar gráficas<br>
<br>
Imprime los valores de los indicadores para México, eliminando la columna del país)<br>
Muestra los países con esperanza de vida femenina mayor al promedio general y sus datos<br>
Muestra los países cuya seguridad al caminar en la noche es menor al promedio y sus valores<br>
Muestra las columnas de los datos completos de los países con mejor satisfacción de vida.<br>

In [10]:
OCDE2=OCDE

# Imprime los valores de los indicadores para México, eliminando la columna del país

In [11]:
#Imprime los valores de los indicadores para México, eliminando la columna del país) 
OCDE2=pd.read_csv('BLI.csv')

In [12]:
#indexar en base al indicador Mexico
IndexPaises= OCDE2.set_index(['Country'])

In [13]:
pd.DataFrame(IndexPaises)

,LOCATION,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Country,,,,,,,,,,,,,,,,
Australia,AUS,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
Austria,AUT,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
Belgium,BEL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
Canada,CAN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.90,NaN,NaN
Czech Republic,CZE,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
Denmark,DNK,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.30,NaN,NaN
Finland,FIN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
France,FRA,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.00,NaN,NaN
Germany,DEU,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.00,NaN,NaN
Greece,GRC,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.40,NaN,NaN
Hungary,HUN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.80,NaN,NaN
Iceland,ISL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
Ireland,IRL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
Italy,ITA,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,8.10,NaN,NaN
Japan,JPN,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.50,NaN,NaN
Korea,KOR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.40,NaN,NaN
Luxembourg,LUX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.20,NaN,NaN
Mexico,MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
Netherlands,NLD,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.10,NaN,NaN
New Zealand,NZL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.90,NaN,NaN
Norway,NOR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.70,NaN,NaN
Poland,POL,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.30,NaN,NaN
Portugal,PRT,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.50,NaN,NaN
Slovak Republic,SVK,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,6.70,NaN,NaN
Spain,ESP,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,17.30,NaN,NaN
Sweden,SWE,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,5.70,NaN,NaN
Switzerland,CHE,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,1.80,NaN,NaN
Turkey,TUR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,13.00,NaN,NaN
United Kingdom,GBR,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,2.60,NaN,NaN
United States,USA,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,3.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Greece,GRC,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.42,E,Estimated value
Hungary,HUN,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.82,E,Estimated value
Iceland,ISL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.87,E,Estimated value
Ireland,IRL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.06,E,Estimated value
Italy,ITA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.29,NaN,NaN
Japan,JPN,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.53,NaN,NaN
Korea,KOR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.00,NaN,NaN
Luxembourg,LUX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.92,E,Estimated value
Mexico,MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value
Netherlands,NLD,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.71,E,Estimated value
New Zealand,NZL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.95,NaN,NaN
Norway,NOR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.65,NaN,NaN
Poland,POL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.08,NaN,NaN
Portugal,PRT,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.64,E,Estimated value
Slovak Republic,SVK,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.77,E,Estimated value
Spain,ESP,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.48,NaN,NaN
Sweden,SWE,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,15.23,NaN,NaN
Switzerland,CHE,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.78,E,Estimated value
Turkey,TUR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.22,E,Estimated value
United Kingdom,GBR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.86,NaN,NaN
United States,USA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.39,NaN,NaN
Brazil,BRA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.18,E,Estimated value
Chile,CHL,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
Estonia,EST,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.43,NaN,NaN
Israel,ISR,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.63,E,Estimated value
Latvia,LVA,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,13.45,NaN,NaN
Russia,RUS,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.66,E,Estimated value
Slovenia,SVN,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.17,NaN,NaN
South Africa,ZAF,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.37,NaN,NaN
OECD - Total,OECD,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,14.60,NaN,NaN

In [14]:
IndicadoresMexico= IndexPaises.loc['Mexico']
pd.DataFrame(IndicadoresMexico)

,LOCATION,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Country,,,,,,,,,,,,,,,,
Mexico,MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
Mexico,MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,3.50,NaN,NaN
Mexico,MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
Mexico,MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
Mexico,MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.90,NaN,NaN
Mexico,MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,48.20,NaN,NaN
Mexico,MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.60,NaN,NaN
Mexico,MEX,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.20,NaN,NaN
Mexico,MEX,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
Mexico,MEX,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
Mexico,MEX,HO_HISH,Housing expenditure,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,21.00,NaN,NaN
Mexico,MEX,HO_HISH,Housing expenditure,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
Mexico,MEX,HO_HISH,Housing expenditure,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
Mexico,MEX,HO_NUMR,Rooms per person,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,1.00,NaN,NaN
Mexico,MEX,HO_NUMR,Rooms per person,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
Mexico,MEX,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
Mexico,MEX,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,13891.00,NaN,NaN
Mexico,MEX,IW_HADI,Household net adjusted disposable income,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
Mexico,MEX,IW_HADI,Household net adjusted disposable income,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
Mexico,MEX,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,Units,NaN,NaN,35912.00,E,Estimated value
Mexico,MEX,IW_HADI,Household net adjusted disposable income,L,Value,LW,Low,USD,US Dollar,0,Units,NaN,NaN,3444.00,E,Estimated value
Mexico,MEX,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
Mexico,MEX,IW_HNFW,Household net financial wealth,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
Mexico,MEX,IW_HNFW,Household net financial wealth,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
Mexico,MEX,JE_EMPL,Employment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.00,NaN,NaN
Mexico,MEX,JE_EMPL,Employment rate,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,79.00,NaN,NaN
Mexico,MEX,JE_EMPL,Employment rate,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.00,NaN,NaN
Mexico,MEX,JE_EMPL,Employment rate,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,80.00,E,Estimated value
Mexico,MEX,JE_EMPL,Employment rate,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,65.00,E,Estimated value
Mexico,MEX,JE_LTUR,Long-term unemployment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,0.08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mexico,MEX,EQ_WATER,Water quality,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
Mexico,MEX,EQ_WATER,Water quality,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
Mexico,MEX,EQ_WATER,Water quality,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,68.00,NaN,NaN
Mexico,MEX,CG_VOTO,Voter turnout,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.00,NaN,NaN
Mexico,MEX,CG_VOTO,Voter turnout,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
Mexico,MEX,CG_VOTO,Voter turnout,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
Mexico,MEX,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
Mexico,MEX,CG_VOTO,Voter turnout,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
Mexico,MEX,HS_LEB,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.00,NaN,NaN
Mexico,MEX,HS_LEB,Life expectancy,L,Value,MN,Men,YR,Years,0,Units,NaN,NaN,72.30,NaN,NaN
Mexico,MEX,HS_LEB,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.70,NaN,NaN
Mexico,MEX,HS_SFRH,Self-reported health,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
Mexico,MEX,HS_SFRH,Self-reported health,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
Mexico,MEX,HS_SFRH,Self-reported health,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,64.00,NaN,NaN
Mexico,MEX,HS_SFRH,Self-reported health,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,78.00,E,Estimated value
Mexico,MEX,HS_SFRH,Self-reported health,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,57.00,E,Estimated value
Mexico,MEX,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
Mexico,MEX,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,6.50,NaN,NaN
Mexico,MEX,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
Mexico,MEX,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.40,NaN,NaN
Mexico,MEX,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.10,NaN,NaN
Mexico,MEX,PS_REPH,Homicide rate,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,17.90,NaN,NaN
Mexico,MEX,PS_REPH,Homicide rate,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,33.50,NaN,NaN
Mexico,MEX,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,4.20,NaN,NaN
Mexico,MEX,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,29.48,NaN,NaN
Mexico,MEX,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,36.27,NaN,NaN
Mexico,MEX,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,18.39,NaN,NaN
Mexico,MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,TOT,Total,HOUR,Hours,0,Units,NaN,NaN,12.74,E,Estimated value
Mexico,MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,MN,Men,HOUR,Hours,0,Units,NaN,NaN,13.03,E,Estimated value
Mexico,MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value

In [15]:
#Imprime los valores de los indicadores para México, eliminando la columna del país) 
#en esta parte al cambiar el indice de Country a otra columna, en este caso seleccioné 'LOCATION'
#y automaticamente me borra el indice de 'Country' al cambiar de indice a otro
Mexico= IndicadoresMexico.set_index(['LOCATION'])

In [47]:
pd.DataFrame(Mexico)

,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,
MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,3.50,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.90,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,48.20,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.60,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,21.00,NaN,NaN
MEX,HO_HISH,Housing expenditure,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,1.00,NaN,NaN
MEX,HO_NUMR,Rooms per person,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,13891.00,NaN,NaN
MEX,IW_HADI,Household net adjusted disposable income,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,Units,NaN,NaN,35912.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,LW,Low,USD,US Dollar,0,Units,NaN,NaN,3444.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,79.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,80.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,65.00,E,Estimated value
MEX,JE_LTUR,Long-term unemployment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,0.08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MEX,EQ_WATER,Water quality,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,68.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,HS_LEB,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.00,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,MN,Men,YR,Years,0,Units,NaN,NaN,72.30,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.70,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,64.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,78.00,E,Estimated value
MEX,HS_SFRH,Self-reported health,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,57.00,E,Estimated value
MEX,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,6.50,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.40,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.10,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,17.90,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,33.50,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,29.48,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,36.27,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,18.39,NaN,NaN
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,TOT,Total,HOUR,Hours,0,Units,NaN,NaN,12.74,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,MN,Men,HOUR,Hours,0,Units,NaN,NaN,13.03,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value

In [48]:
#Borro una columna solo para ver si se puede jejejeje
MexsinRPC=Mexico.drop(['Reference Period Code'],axis=1)
#pd.DataFrame(Mexico)

In [51]:
pd.DataFrame(MexsinRPC)

,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,
MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,4.60,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,3.50,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,3.50,E,Estimated value
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,3.50,E,Estimated value
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,45.90,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,MN,Men,PC,Percentage,0,Units,NaN,48.20,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,43.60,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,4.20,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,Units,NaN,4.20,E,Estimated value
MEX,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,4.20,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,21.00,NaN,NaN
MEX,HO_HISH,Housing expenditure,L,Value,MN,Men,PC,Percentage,0,Units,NaN,21.00,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,21.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,1.00,NaN,NaN
MEX,HO_NUMR,Rooms per person,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,1.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,1.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,13891.00,NaN,NaN
MEX,IW_HADI,Household net adjusted disposable income,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,Units,NaN,35912.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,LW,Low,USD,US Dollar,0,Units,NaN,3444.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,4750.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,61.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,MN,Men,PC,Percentage,0,Units,NaN,79.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,45.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,HGH,High,PC,Percentage,0,Units,NaN,80.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,LW,Low,PC,Percentage,0,Units,NaN,65.00,E,Estimated value
MEX,JE_LTUR,Long-term unemployment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,0.08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MEX,EQ_WATER,Water quality,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,67.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,MN,Men,PC,Percentage,0,Units,NaN,66.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,68.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,63.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,MN,Men,PC,Percentage,0,Units,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,Units,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,LW,Low,PC,Percentage,0,Units,NaN,63.00,E,Estimated value
MEX,HS_LEB,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,75.00,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,MN,Men,YR,Years,0,Units,NaN,72.30,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,77.70,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,66.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,MN,Men,PC,Percentage,0,Units,NaN,67.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,64.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,HGH,High,PC,Percentage,0,Units,NaN,78.00,E,Estimated value
MEX,HS_SFRH,Self-reported health,L,Value,LW,Low,PC,Percentage,0,Units,NaN,57.00,E,Estimated value
MEX,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,6.50,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,7.40,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,6.10,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,17.90,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,33.50,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,4.20,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,29.48,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,NaN,36.27,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,18.39,NaN,NaN
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,TOT,Total,HOUR,Hours,0,Units,NaN,12.74,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,MN,Men,HOUR,Hours,0,Units,NaN,13.03,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,12.39,E,Estimated value

In [52]:
#Muestra los países con esperanza de vida mayor al promedio general y sus datos
#Indicator 'Life expectancy'

#indexar en base al indicador 'Indicator'
IndexEsperanzaVida=OCDE2.set_index(['Indicator'])

In [53]:
#Life expectancy
EsperanzaVida= IndexEsperanzaVida.loc['Life expectancy']
pd.DataFrame(EsperanzaVida)

,LOCATION,Country,INDICATOR,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Indicator,,,,,,,,,,,,,,,,
Life expectancy,AUS,Australia,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
Life expectancy,AUT,Austria,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.3,NaN,NaN
Life expectancy,BEL,Belgium,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
Life expectancy,CAN,Canada,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
Life expectancy,CZE,Czech Republic,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.7,NaN,NaN
Life expectancy,DNK,Denmark,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,80.8,NaN,NaN
Life expectancy,FIN,Finland,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Life expectancy,FRA,France,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
Life expectancy,DEU,Germany,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
Life expectancy,GRC,Greece,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
Life expectancy,HUN,Hungary,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.7,NaN,NaN
Life expectancy,ISL,Iceland,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
Life expectancy,IRL,Ireland,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
Life expectancy,ITA,Italy,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.6,NaN,NaN
Life expectancy,JPN,Japan,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
Life expectancy,KOR,Korea,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.1,NaN,NaN
Life expectancy,LUX,Luxembourg,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
Life expectancy,MEX,Mexico,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.0,NaN,NaN
Life expectancy,NLD,Netherlands,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Life expectancy,NZL,New Zealand,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
Life expectancy,NOR,Norway,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
Life expectancy,POL,Poland,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,77.6,NaN,NaN
Life expectancy,PRT,Portugal,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
Life expectancy,SVK,Slovak Republic,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
Life expectancy,ESP,Spain,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
Life expectancy,SWE,Sweden,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.3,NaN,NaN
Life expectancy,CHE,Switzerland,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
Life expectancy,TUR,Turkey,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.0,NaN,NaN
Life expectancy,GBR,United Kingdom,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.0,NaN,NaN
Life expectancy,USA,United States,HS_LEB,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Life expectancy,GRC,Greece,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Life expectancy,HUN,Hungary,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,79.0,NaN,NaN
Life expectancy,ISL,Iceland,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.8,NaN,NaN
Life expectancy,IRL,Ireland,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Life expectancy,ITA,Italy,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.9,NaN,NaN
Life expectancy,JPN,Japan,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,87.1,NaN,NaN
Life expectancy,KOR,Korea,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.2,NaN,NaN
Life expectancy,LUX,Luxembourg,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.7,NaN,NaN
Life expectancy,MEX,Mexico,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.7,NaN,NaN
Life expectancy,NLD,Netherlands,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.2,NaN,NaN
Life expectancy,NZL,New Zealand,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Life expectancy,NOR,Norway,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.2,NaN,NaN
Life expectancy,POL,Poland,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Life expectancy,PRT,Portugal,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.3,NaN,NaN
Life expectancy,SVK,Slovak Republic,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,80.2,NaN,NaN
Life expectancy,ESP,Spain,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.8,NaN,NaN
Life expectancy,SWE,Sweden,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Life expectancy,CHE,Switzerland,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.1,NaN,NaN
Life expectancy,TUR,Turkey,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
Life expectancy,GBR,United Kingdom,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.8,NaN,NaN
Life expectancy,USA,United States,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
Life expectancy,BRA,Brazil,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,78.5,NaN,NaN
Life expectancy,CHL,Chile,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
Life expectancy,EST,Estonia,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.2,NaN,NaN
Life expectancy,ISR,Israel,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Life expectancy,LVA,Latvia,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,79.5,NaN,NaN
Life expectancy,RUS,Russia,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
Life expectancy,SVN,Slovenia,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
Life expectancy,ZAF,South Africa,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,59.5,NaN,NaN
Life expectancy,OECD,OECD - Total,HS_LEB,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN

# Muestra los países con esperanza de vida femenina mayor al promedio general y sus datos

In [54]:
#Muestra los países con esperanza de vida femenina mayor al promedio general y sus datos
#Indicator 'Life expectancy'

#indexar en base al indicador 'Indicator'
IndexEsperanzaVidaFemenina=EsperanzaVida.set_index(['Inequality'])

In [55]:
#Muestro el dataset para ver los cambios
IndexEsperanzaVidaFemenina

,LOCATION,Country,INDICATOR,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,
Total,AUS,Australia,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
Total,AUT,Austria,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.3,NaN,NaN
Total,BEL,Belgium,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
Total,CAN,Canada,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
Total,CZE,Czech Republic,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,78.7,NaN,NaN
Total,DNK,Denmark,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,80.8,NaN,NaN
Total,FIN,Finland,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Total,FRA,France,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
Total,DEU,Germany,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
Total,GRC,Greece,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
Total,HUN,Hungary,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,75.7,NaN,NaN
Total,ISL,Iceland,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
Total,IRL,Ireland,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
Total,ITA,Italy,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.6,NaN,NaN
Total,JPN,Japan,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
Total,KOR,Korea,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.1,NaN,NaN
Total,LUX,Luxembourg,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
Total,MEX,Mexico,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,75.0,NaN,NaN
Total,NLD,Netherlands,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Total,NZL,New Zealand,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
Total,NOR,Norway,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
Total,POL,Poland,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,77.6,NaN,NaN
Total,PRT,Portugal,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
Total,SVK,Slovak Republic,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
Total,ESP,Spain,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
Total,SWE,Sweden,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,82.3,NaN,NaN
Total,CHE,Switzerland,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
Total,TUR,Turkey,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,78.0,NaN,NaN
Total,GBR,United Kingdom,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,81.0,NaN,NaN
Total,USA,United States,HS_LEB,L,Value,TOT,YR,Years,0,Units,NaN,NaN,78.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Women,GRC,Greece,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Women,HUN,Hungary,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,79.0,NaN,NaN
Women,ISL,Iceland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.8,NaN,NaN
Women,IRL,Ireland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,ITA,Italy,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.9,NaN,NaN
Women,JPN,Japan,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,87.1,NaN,NaN
Women,KOR,Korea,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.2,NaN,NaN
Women,LUX,Luxembourg,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.7,NaN,NaN
Women,MEX,Mexico,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,77.7,NaN,NaN
Women,NLD,Netherlands,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.2,NaN,NaN
Women,NZL,New Zealand,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,NOR,Norway,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.2,NaN,NaN
Women,POL,Poland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Women,PRT,Portugal,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.3,NaN,NaN
Women,SVK,Slovak Republic,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,80.2,NaN,NaN
Women,ESP,Spain,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.8,NaN,NaN
Women,SWE,Sweden,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,CHE,Switzerland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.1,NaN,NaN
Women,TUR,Turkey,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
Women,GBR,United Kingdom,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.8,NaN,NaN
Women,USA,United States,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
Women,BRA,Brazil,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,78.5,NaN,NaN
Women,CHL,Chile,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
Women,EST,Estonia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.2,NaN,NaN
Women,ISR,Israel,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,LVA,Latvia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,79.5,NaN,NaN
Women,RUS,Russia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
Women,SVN,Slovenia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
Women,ZAF,South Africa,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,59.5,NaN,NaN
Women,OECD,OECD - Total,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN

In [68]:
#Filtro los registros con la esperanza de vida de las mujeres solamente
#Women Life expectancy
EsperanzaVidaFemenina= IndexEsperanzaVidaFemenina.loc['Women']

In [69]:
#muestro mi dataset para ver los cambios
pd.DataFrame(EsperanzaVidaFemenina)

,LOCATION,Country,INDICATOR,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,
Women,AUS,Australia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.5,NaN,NaN
Women,AUT,Austria,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Women,BEL,Belgium,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,CAN,Canada,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.6,NaN,NaN
Women,CZE,Czech Republic,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Women,DNK,Denmark,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN
Women,FIN,Finland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.4,NaN,NaN
Women,FRA,France,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.5,NaN,NaN
Women,DEU,Germany,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.1,NaN,NaN
Women,GRC,Greece,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Women,HUN,Hungary,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,79.0,NaN,NaN
Women,ISL,Iceland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.8,NaN,NaN
Women,IRL,Ireland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,ITA,Italy,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.9,NaN,NaN
Women,JPN,Japan,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,87.1,NaN,NaN
Women,KOR,Korea,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.2,NaN,NaN
Women,LUX,Luxembourg,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.7,NaN,NaN
Women,MEX,Mexico,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,77.7,NaN,NaN
Women,NLD,Netherlands,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.2,NaN,NaN
Women,NZL,New Zealand,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,NOR,Norway,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.2,NaN,NaN
Women,POL,Poland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Women,PRT,Portugal,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.3,NaN,NaN
Women,SVK,Slovak Republic,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,80.2,NaN,NaN
Women,ESP,Spain,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.8,NaN,NaN
Women,SWE,Sweden,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,CHE,Switzerland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.1,NaN,NaN
Women,TUR,Turkey,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
Women,GBR,United Kingdom,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.8,NaN,NaN
Women,USA,United States,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
Women,BRA,Brazil,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,78.5,NaN,NaN
Women,CHL,Chile,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
Women,EST,Estonia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.2,NaN,NaN
Women,ISR,Israel,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,LVA,Latvia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,79.5,NaN,NaN
Women,RUS,Russia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
Women,SVN,Slovenia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
Women,ZAF,South Africa,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,59.5,NaN,NaN
Women,OECD,OECD - Total,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN

In [60]:
#Muestro los datos estadisticos de la esperanza de vida femenina en 39 paises
EsperanzaVidaFemenina.describe()

       PowerCode Code  Reference Period Code  Reference Period      Value
count            39.0                    0.0               0.0  39.000000
mean              0.0                    NaN               NaN  82.241026
std               0.0                    NaN               NaN   4.378880
min               0.0                    NaN               NaN  59.500000
25%               0.0                    NaN               NaN  81.600000
50%               0.0                    NaN               NaN  83.400000
75%               0.0                    NaN               NaN  84.250000
max               0.0                    NaN               NaN  87.100000

In [64]:
promvidamujeres=round(sum(EsperanzaVidaFemenina['Value'])/len(EsperanzaVidaFemenina),2)
print("El promedio de vida de mujeres es {} años".format(promvidamujeres))

El promedio de vida de mujeres es 82.24 años

In [84]:
#Muestra los países con esperanza de vida femenina mayor al promedio general y sus datos

#comparo todos los registros de la columna 'value' del dataset EsperanzaVidaFemenina para que solo 
#filtre los que son mayores al promedio, que en este caso es 82.24
Esp_Vida_arriba_Prom = EsperanzaVidaFemenina[EsperanzaVidaFemenina['Value'] > 82.24 ]

#presento la información en pantalla, bonita y explicada
print("Existen {} paises cuya esperanza de vida para mujeres supera el promedio".format(len(Esp_Vida_arriba_Prom)))
print("A continuación de muestran ordenados de mayor a menor")

#ordeno el dataset con sort_values, checar la sintaxis del sort
Esp_Vida_arriba_Prom.sort_values(by=['Value'],axis=0,ascending=False)

Existen 26 paises cuya esperanza de vida para mujeres supera el promedio
A continuación de muestran ordenados de mayor a menor

,LOCATION,Country,INDICATOR,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,
Women,JPN,Japan,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,87.1,NaN,NaN
Women,ESP,Spain,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.8,NaN,NaN
Women,FRA,France,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.5,NaN,NaN
Women,KOR,Korea,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.2,NaN,NaN
Women,CHE,Switzerland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.1,NaN,NaN
Women,ITA,Italy,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.9,NaN,NaN
Women,LUX,Luxembourg,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.7,NaN,NaN
Women,AUS,Australia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.5,NaN,NaN
Women,FIN,Finland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.4,NaN,NaN
Women,PRT,Portugal,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.3,NaN,NaN
Women,NOR,Norway,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.2,NaN,NaN
Women,ISR,Israel,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,SWE,Sweden,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,SVN,Slovenia,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
Women,ISL,Iceland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.8,NaN,NaN
Women,GRC,Greece,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Women,AUT,Austria,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Women,CAN,Canada,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.6,NaN,NaN
Women,NZL,New Zealand,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,BEL,Belgium,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,IRL,Ireland,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,NLD,Netherlands,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.2,NaN,NaN
Women,DEU,Germany,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.1,NaN,NaN
Women,GBR,United Kingdom,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.8,NaN,NaN
Women,DNK,Denmark,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN
Women,OECD,OECD - Total,HS_LEB,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN


<br><br>

# Muestra los países cuya seguridad al caminar en la noche es menor al promedio y sus valores

In [86]:
#Creo un nuevo dataset para manipularlo
OCDESeguridad=OCDE

In [88]:
#Filtrar en base al indicador 'Feeling safe walking alone at night' SIN CAMBIAR EL INDICE
DataSetSeguridad=OCDESeguridad[OCDESeguridad['Indicator'] =='Feeling safe walking alone at night'] 
DataSetSeguridad

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
154,AUS,Australia,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.6,NaN,NaN
155,AUT,Austria,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,80.7,NaN,NaN
156,BEL,Belgium,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,70.7,NaN,NaN
157,CAN,Canada,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,80.9,NaN,NaN
158,CZE,Czech Republic,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,68.3,NaN,NaN
159,DNK,Denmark,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,83.0,NaN,NaN
160,FIN,Finland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,82.9,NaN,NaN
161,FRA,France,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,69.6,NaN,NaN
162,DEU,Germany,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,75.9,NaN,NaN
163,GRC,Greece,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.8,NaN,NaN
164,HUN,Hungary,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,50.7,NaN,NaN
165,ISL,Iceland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,87.0,NaN,NaN
166,IRL,Ireland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,75.5,NaN,NaN
167,ITA,Italy,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,58.3,NaN,NaN
168,JPN,Japan,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,70.6,NaN,NaN
169,KOR,Korea,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.9,NaN,NaN
170,LUX,Luxembourg,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,72.0,NaN,NaN
171,MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.9,NaN,NaN
172,NLD,Netherlands,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,81.2,NaN,NaN
173,NZL,New Zealand,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,64.8,NaN,NaN
174,NOR,Norway,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,87.7,NaN,NaN
175,POL,Poland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.3,NaN,NaN
176,PRT,Portugal,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,72.1,NaN,NaN
177,SVK,Slovak Republic,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,60.1,NaN,NaN
178,ESP,Spain,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,83.1,NaN,NaN
179,SWE,Sweden,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,75.9,NaN,NaN
180,CHE,Switzerland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,84.0,NaN,NaN
181,TUR,Turkey,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,60.6,NaN,NaN
182,GBR,United Kingdom,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,77.4,NaN,NaN
183,USA,United States,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,74.1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,GRC,Greece,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,52.1,NaN,NaN
242,HUN,Hungary,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,42.0,NaN,NaN
243,ISL,Iceland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,79.9,NaN,NaN
244,IRL,Ireland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,66.5,NaN,NaN
245,ITA,Italy,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,51.3,NaN,NaN
246,JPN,Japan,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,61.4,NaN,NaN
247,KOR,Korea,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,58.0,NaN,NaN
248,LUX,Luxembourg,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,65.8,NaN,NaN
249,MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.6,NaN,NaN
250,NLD,Netherlands,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,71.9,NaN,NaN
251,NZL,New Zealand,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,51.5,NaN,NaN
252,NOR,Norway,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,79.6,NaN,NaN
253,POL,Poland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,57.7,NaN,NaN
254,PRT,Portugal,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,61.2,NaN,NaN
255,SVK,Slovak Republic,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,51.2,NaN,NaN
256,ESP,Spain,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,79.2,NaN,NaN
257,SWE,Sweden,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.4,NaN,NaN
258,CHE,Switzerland,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,77.7,NaN,NaN
259,TUR,Turkey,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,52.0,NaN,NaN
260,GBR,United Kingdom,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,73.9,NaN,NaN
261,USA,United States,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.3,NaN,NaN
262,BRA,Brazil,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,29.2,NaN,NaN
263,CHL,Chile,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,47.3,NaN,NaN
264,EST,Estonia,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,59.1,NaN,NaN
265,ISR,Israel,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.8,NaN,NaN
266,LVA,Latvia,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,52.9,NaN,NaN
267,RUS,Russia,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.3,NaN,NaN
268,SVN,Slovenia,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,76.6,NaN,NaN
269,ZAF,South Africa,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,28.9,NaN,NaN
270,OECD,OECD - Total,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,60.8,NaN,NaN

In [89]:
#Mostrar la estadística descriptiva de ese indicador para sacar el promedio
DataSetSeguridad.describe()

       PowerCode Code  Reference Period Code  Reference Period       Value
count           117.0                    0.0               0.0  117.000000
mean              0.0                    NaN               NaN   68.845299
std               0.0                    NaN               NaN   14.706458
min               0.0                    NaN               NaN   28.900000
25%               0.0                    NaN               NaN   60.600000
50%               0.0                    NaN               NaN   70.400000
75%               0.0                    NaN               NaN   79.700000
max               0.0                    NaN               NaN   95.600000

In [91]:
#Me estan estresando tantas columns, borraré algunas para hacer espacio
DataSetSeguridad= DataSetSeguridad.drop(['MEASURE','Unit Code','PowerCode Code','Reference Period Code','Reference Period','Flag Codes'],axis=1)

In [93]:
#Crear un dataset filtrado donde solo aparezcan los paises que se encuentran por abajo de promedio de mi indicador 
#'Feeling safe walking alone at night'
PaisesInseguros=DataSetSeguridad[DataSetSeguridad['Value']<68.8452]
print("Muestra los países cuya seguridad al caminar en la noche es menor al promedio y sus valores")
PaisesInseguros.sort_values(by=['Value'],axis=0,ascending=False)

Muestra los países cuya seguridad al caminar en la noche es menor al promedio y sus valores

,LOCATION,Country,INDICATOR,Indicator,Measure,INEQUALITY,Inequality,Unit,PowerCode,Value,Flags
192,OECD,OECD - Total,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,68.6,NaN
158,CZE,Czech Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,68.3,NaN
240,DEU,Germany,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,68.0,NaN
186,EST,Estonia,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,67.2,NaN
244,IRL,Ireland,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,66.5,NaN
175,POL,Poland,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,66.3,NaN
206,ITA,Italy,PS_FSAFEN,Feeling safe walking alone at night,Value,MN,Men,Percentage,Units,66.1,NaN
248,LUX,Luxembourg,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,65.8,NaN
239,FRA,France,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,64.9,NaN
173,NZL,New Zealand,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,64.8,NaN
169,KOR,Korea,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,63.9,NaN
265,ISR,Israel,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,63.8,NaN
154,AUS,Australia,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,63.6,NaN
257,SWE,Sweden,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,63.4,NaN
261,USA,United States,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,63.3,NaN
163,GRC,Greece,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,61.8,NaN
246,JPN,Japan,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,61.4,NaN
254,PRT,Portugal,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,61.2,NaN
234,BEL,Belgium,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,61.1,NaN
228,RUS,Russia,PS_FSAFEN,Feeling safe walking alone at night,Value,MN,Men,Percentage,Units,61.0,NaN
203,HUN,Hungary,PS_FSAFEN,Feeling safe walking alone at night,Value,MN,Men,Percentage,Units,60.9,NaN
270,OECD,OECD - Total,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,60.8,NaN
188,LVA,Latvia,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,60.7,NaN
181,TUR,Turkey,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,60.6,NaN
177,SVK,Slovak Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,60.1,NaN
236,CZE,Czech Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,59.6,NaN
264,EST,Estonia,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,59.1,NaN
167,ITA,Italy,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,58.3,NaN
247,KOR,Korea,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,58.0,NaN
253,POL,Poland,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,57.7,NaN
224,CHL,Chile,PS_FSAFEN,Feeling safe walking alone at night,Value,MN,Men,Percentage,Units,55.1,NaN
266,LVA,Latvia,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,52.9,NaN
189,RUS,Russia,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,52.2,NaN
241,GRC,Greece,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,52.1,NaN
259,TUR,Turkey,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,52.0,NaN
251,NZL,New Zealand,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,51.5,NaN
245,ITA,Italy,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,51.3,NaN
255,SVK,Slovak Republic,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,51.2,NaN
185,CHL,Chile,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,51.1,NaN
164,HUN,Hungary,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,50.7,NaN
232,AUS,Australia,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,49.9,NaN
210,MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,Value,MN,Men,Percentage,Units,48.2,NaN
263,CHL,Chile,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,47.3,NaN
171,MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,45.9,NaN
223,BRA,Brazil,PS_FSAFEN,Feeling safe walking alone at night,Value,MN,Men,Percentage,Units,45.9,NaN
267,RUS,Russia,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,45.3,NaN
230,ZAF,South Africa,PS_FSAFEN,Feeling safe walking alone at night,Value,MN,Men,Percentage,Units,43.8,NaN
249,MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,43.6,NaN
242,HUN,Hungary,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,42.0,NaN
184,BRA,Brazil,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,37.3,NaN
191,ZAF,South Africa,PS_FSAFEN,Feeling safe walking alone at night,Value,TOT,Total,Percentage,Units,36.1,NaN
262,BRA,Brazil,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,29.2,NaN
269,ZAF,South Africa,PS_FSAFEN,Feeling safe walking alone at night,Value,WMN,Women,Percentage,Units,28.9,NaN




# Muestra las columnas de los datos completos de los países con mejor satisfacción de vida

In [95]:
#Filtrar en base al indicador 'Life satisfaction' SIN CAMBIAR EL INDICE
#aqui no cree un dataset nuevo previo, directo estoy usando el OCDE total no lo estoy modificando, sin embargo
#SI lo lmaceno en una variable nueva llmada SatisfaccVida para modificarla
SatisfaccVida=OCDE[OCDE['Indicator'] =='Life satisfaction'] 
#Ordeno mi dataset de mejor calidad de vida a menor
SatisfaccVida.sort_values(by=['Value'],axis=0,ascending=False)

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
2982,FIN,Finland,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,8.0,NaN,NaN
2987,ISL,Iceland,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,8.0,NaN,NaN
2996,NOR,Norway,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.8,NaN,NaN
3002,CHE,Switzerland,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.8,NaN,NaN
2981,DNK,Denmark,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.8,NaN,NaN
2943,FIN,Finland,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.7,NaN,NaN
2994,NLD,Netherlands,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.6,NaN,NaN
3001,SWE,Sweden,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.6,NaN,NaN
2942,DNK,Denmark,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.6,NaN,NaN
2957,NOR,Norway,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.6,NaN,NaN
2979,CAN,Canada,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.6,NaN,NaN
2995,NZL,New Zealand,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2879,NOR,Norway,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2909,ISL,Iceland,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2918,NOR,Norway,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
3006,CHL,Chile,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2885,CHE,Switzerland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2977,AUT,Austria,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2903,DNK,Denmark,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2870,ISL,Iceland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2924,CHE,Switzerland,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2948,ISL,Iceland,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2976,AUS,Australia,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2864,DNK,Denmark,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2865,FIN,Finland,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2963,CHE,Switzerland,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
2940,CAN,Canada,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
2937,AUS,Australia,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
2955,NLD,Netherlands,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
3030,NOR,Norway,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2964,TUR,Turkey,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
3024,ITA,Italy,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
2969,EST,Estonia,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
2891,EST,Estonia,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
2913,KOR,Korea,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
3025,JPN,Japan,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.5,NaN,NaN
2886,TUR,Turkey,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.5,NaN,NaN
2925,TUR,Turkey,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,5.4,NaN,NaN
3042,LVA,Latvia,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.4,NaN,NaN
2908,HUN,Hungary,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
2947,HUN,Hungary,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
2946,GRC,Greece,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
2959,PRT,Portugal,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
2869,HUN,Hungary,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
2868,GRC,Greece,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
3044,SVN,Slovenia,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
3041,EST,Estonia,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
3037,TUR,Turkey,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
3031,POL,Poland,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
2881,PRT,Portugal,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
3026,KOR,Korea,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.1,NaN,NaN
2920,PRT,Portugal,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,5.1,NaN,NaN
2907,GRC,Greece,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,5.1,NaN,NaN
2935,ZAF,South Africa,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,4.9,NaN,NaN
2896,ZAF,South Africa,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,4.8,NaN,NaN
2974,ZAF,South Africa,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,4.8,NaN,NaN
3021,HUN,Hungary,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.8,NaN,NaN
3032,PRT,Portugal,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.5,NaN,NaN
3020,GRC,Greece,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.3,NaN,NaN
3045,ZAF,South Africa,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.2,NaN,NaN

In [96]:
SatisfaccVida.describe()

       PowerCode Code  Reference Period Code  Reference Period       Value
count           188.0                    0.0               0.0  188.000000
mean              0.0                    NaN               NaN    6.543085
std               0.0                    NaN               NaN    0.824170
min               0.0                    NaN               NaN    4.200000
25%               0.0                    NaN               NaN    5.900000
50%               0.0                    NaN               NaN    6.600000
75%               0.0                    NaN               NaN    7.300000
max               0.0                    NaN               NaN    8.000000